#!/bin/bash
# Manual CLI Test Script
# 1. Reset DB
rm -f sophia.db
rm -f data/error_patterns.jsonl

# 2. Ingest
echo "=== 1. Ingest ==="
PYTHONPATH=. /Users/dragonpd/Sophia/.venv/bin/python core/engine/cli.py ingest "chat_test_001" > ingest_out.txt
EP_ID=$(cat ingest_out.txt | grep "Created Episode" | awk '{print $3}')
echo "Episode ID: $EP_ID"

# 3. Propose (with high confidence text)
echo "=== 2. Propose (High Confidence) ==="
PYTHONPATH=. /Users/dragonpd/Sophia/.venv/bin/python core/engine/cli.py propose "$EP_ID" --text "This is a timeless principle." > propose_out.txt
cat propose_out.txt
CAND_ID=$(grep "cand_" propose_out.txt | head -n 1 | awk '{print $2}' | sed 's/://')
echo "Candidate ID: $CAND_ID"

# 4. Adopt
echo "=== 3. Adopt ==="
PYTHONPATH=. /Users/dragonpd/Sophia/.venv/bin/python core/engine/cli.py adopt "$EP_ID" "$CAND_ID"

# 5. Propose Low Confidence (Fallback)
echo "=== 4. Propose (Low Confidence) ==="
PYTHONPATH=. /Users/dragonpd/Sophia/.venv/bin/python core/engine/cli.py propose "$EP_ID" --text "Just some random noise." > propose_low.txt
cat propose_low.txt
CAND_LOW=$(grep "cand_" propose_low.txt | head -n 1 | awk '{print $2}' | sed 's/://')

# 6. Reject Low Confidence
echo "=== 5. Reject ==="
PYTHONPATH=. /Users/dragonpd/Sophia/.venv/bin/python core/engine/cli.py reject "$EP_ID" "$CAND_LOW"
echo "Checking error log..."
cat data/error_patterns.jsonl

# 7. Search
echo "=== 6. Search ==="
# Search for TIMELESS (Chunk C = 0x1) - generated by "timeless principle"
# 0x1 << 4 = 0x10. wait, mask search checks `bits_c`.
PYTHONPATH=. /Users/dragonpd/Sophia/.venv/bin/python core/engine/cli.py search --mask_c 1

echo "Done."
